### ISSUE TITLE
First Page: BackGround Design

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#11]
პირველი გვერდის ფონის სურათი, MyAuto-ს ფერებში და სახელით.

**Comment by kujma10-zz** [comment]
მოსაფიქრებელია, როგორი ფონი გაკეთდეს და სავარაუდოდ მოგვიწევს ფოტოშოპით გაკეთება

**Comment by gkiko** [comment]
yvelaze naklebi problemaa jamad eg :-)
