### ISSUE TITLE
Main Page: enis mixedvit gancxadebebis gamotana

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#121]
anu chven exa vicert da gamogvaq marto qartuli varianti, da roca inglisuri enaa archeuli inglisuri xml unda chamovtvirtot, magram ar vici ra ganasxvavebs inglisurs qartulisgan ro chamocero, URL-shi ver vnaxe rame enis ID an ragac egeti  . . .

**Comment by gkiko** [comment]
ფილტრზე ამბობ?

**Comment by Jilberta** [comment]
ara, zogadad manqanebiis sia unda gamodiodes im enaze ra enacaa archeuli . . .

**Comment by gkiko** [comment]
იმედია არ დამავიწყდება ხვალ რომ ვუთხრა :smiley:
