### ISSUE TITLE
Out Of Memory 

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#125]
3-4 sxvadasxva manqanas ro irchev ro detalebi naxo, me-3 tu me-4 ze ukve heap ivseba suratebis gamo . . .     BitMapFactory -s gamo xdeba maxsovrobis gadavseba

**Comment by Jilberta** [comment]
@gkiko

**Comment by gkiko** [comment]
გასაგებლარიან

**Comment by gkiko** [comment]
ეს გაცასწორე იდეაში. @Jilberta -მ უნდა გატესტოს

**Comment by Jilberta** [comment]
Memory Leak gascorebulia, magram XML ufuchdebat imat manqanis detalebis
