### ISSUE TITLE
Car List

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#127]
roca manqanebis siisas xdeba enis shecvla, iCrasheba . . .

Mizezi:  ena roca icvleba, icvleba configuraciac shesabamisad micevs arsebuli Intent-is gadatvirtva, darefresheba,  carList-ze kide info moecodeba sxva Intent-dan da mgoni magis bralia rom gadatvirtvis mere is info ikargeba da icrash-eba

**Comment by Jilberta** [comment]
@gkiko

**Comment by gkiko** [comment]
მაგის მიზეზი რატომ უნდა იყოს? ინტენტში ჩადებული სიას ხომ არაფერი ემართება?!

**Comment by kujma10-zz** [comment]
@Jilberta  chemtan ar icrasheba. zustad dawere aba scenari ra dros icrasheba. 
chemtan manqanis siis ena ar icvleba saertod, marto menus ragaceebi icvleba.
da detalebis gverdzec ucnaur ragaceebs shveba marto naxevar mxares ucvlis enas
