### ISSUE TITLE
ფილტრის დიალოგის ასოები რუსულ ენაზე გაფუჭებულია

### ISSUE THREAD

**Issue by gkiko** [gkiko/MyAuto#128]
მაგალითად კატეგორიების ალერტ დიალოგის გამოჩენისას გაფუჭებული ასიებო ჩანს, თითქოს ვერ იგებს ასოებს

**Comment by Jilberta** [comment]
kikol mgoni shentanaa ragaca problema Padze imito, ro chemtan mushaobs . . .

**Comment by gkiko** [comment]
აპლიკაცია გადავაყენე და გამოსწორდა :confused:
