### ISSUE TITLE
ფილტრის დიალოგზე თუ არაფერს ავირჩევ იქრაშება

### ISSUE THREAD

**Issue by gkiko** [gkiko/MyAuto#129]
თუ ფილტრის გვერდზე დიალოგი გამომიხტა და რამის არჩევის გარეშე _OK_-ს დავაჭერთ, პროგრამა დაიქრაშება.

**Comment by Jilberta** [comment]
kai xar dzmishvilo

**Comment by Jilberta** [comment]
vsio gascorda
