### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by gkiko** [gkiko/MyAuto#141]
თუ ინტერნეტი არაა ჩართული და აპლიკაცია იწყება, იქრაშება

**Comment by gkiko** [comment]
@kujma10 ეს გაასწორე?

**Comment by kujma10-zz** [comment]
არა

**Comment by kujma10-zz** [comment]
@gkiko  რა უნდა გამოვიტანო შეცდომისას აბა?
სად გინახავს აპლიკაციას რო რთავ და უცბად გეუბნება ინტერნეტი არ გაქვს და ვერ შეხვალო

**Comment by kujma10-zz** [comment]
@gkiko  ინტერნეტი გავთიშე და ისე გავუშვი და არ ვარდება შეცდომა.
მგონი ნელი როცაა მაშინ აყოვნებს ხოლმე და ელოდება რაღაცას.

**Comment by gkiko** [comment]
მე დავაკომენტარე შენი კოდი, შემოწმება რომ იყო დალოგინებული ხარ თუ არა. ეგ კომენტარი მოხსენი და ამოვარდება

**Comment by kujma10-zz** [comment]
აღარ ხდება სერვერზე შემოწმება თავიდან

2013/9/21 Giorgi Kikolashvili notifications@github.com

**Comment by gkiko** [comment]
საერთოდ არ გვჭირდება მაგის შემოწმება ჯერ. ბოლოს დავამატებთ
