### ISSUE TITLE
Search Page: tu filtrebshi problemaa

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#143]
tu filtrebshi dialogshi carieli datove da araferi monishne da ise daaceqi ok-s icrasheba imito ro null-s igebs

**Comment by gkiko** [comment]
ადრეც გვქონდა ეგ შეცდომა როგორც მახსოვს და მერე შენ გაასწორე :dart:

**Comment by gkiko** [comment]
:clap:
