### ISSUE TITLE
Log out-ის დროს კვდებოდეს activity და გადადიოდეს მთავარ გვერდზე

### ISSUE THREAD

**Issue by kujma10-zz** [gkiko/MyAuto#144]

**Comment by kujma10-zz** [comment]
@Jilberta  შენი კოდი მჭირდება ამისთვის

**Comment by Jilberta** [comment]
`nextIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);`
`nextIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);`
`startActivity(nextIntent);`
