### ISSUE TITLE
First Page: Button Designs

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#16]
ღილაკებს ჭირდება შესაბამისი დიზაინი, რამე სურათი რო იყოს ღილაკის შესაბამისი მგონი საკმარისი იქნება  . . .

**Comment by kujma10-zz** [comment]
ეს უნდა გაკეთდეს ფონის დაყენების შემდეგ, რომ ღილაკების დიზაინი კარგად მოერგოს ფონს
