### ISSUE TITLE
Main Page: ახალი განცხადებების სია

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#18]
როდესაც მენიუდან ან პირველი გვერდიდან გადმოდის მომხარებელი ამ გვერდზე, მაშინ უნდა გამოვიტანოთ ახალი მანქანების სია. 

ვინც დაიწყებს ამის წერას შეგიძლიათ ეს Issue დაყოთ უფრო პატარებად, ცალკე გადმოწერა, ცალკე გამოტანა და ასე შემდეგ.

გაკეთების ერთი ვარიანტი: შეამოწმებ  თუ Bundle-ს რამე გადმოეცემა ესეგი გაფილტრული უნდა გამოიტანო და გადმოცემული მონაცემის მიხედვით ჩამოტვირთავ სიას და გამოიტან, ხოლო თუ არაფერი გადმოეცემა, მაშინ ესეგი ახალი განცხადებები უნდა გამოიტანო.

**Comment by kujma10-zz** [comment]
@Jilberta  @gkiko  მეორე ტაბი (ფილტრის) საჭიროა ისევ ამ გვერდზე თუ მოვაშალოთ?

**Comment by gkiko** [comment]
piltris tabze unda gadadiode yvitel gverdze search romaa im gilakit

**Comment by kujma10-zz** [comment]
ვეღარ მივხვდი ამ იშუს მიზანი რაღა არის. რაც ავიღე ან სხვა წერს ან უკვე დაწერილია :@ :დ
როგორც მივხვდი მაშინ, ფილტრის ღილაკს რომ ეჭირება ფილტერედაქთივითის ნაცვლად ისევ პირველ ტაბზე უნდა გადადიოდეს, ოღონდ გაფილტრული სიით?

**Comment by kujma10-zz** [comment]
პ.ს ეს ბაგი მარტო მე მაქვს ? სულ ერთიდაიგივე მანქანები გამოაქვს ოღონდ სხვადასხვა სურათებით (დღეს დაემართა ეს!) 
![2013-06-16_145245](https://f.cloud.github.com/assets/2605976/659216/ed4e49f2-d672-11e2-938c-d2ec87f151bf.png)

**Comment by gkiko** [comment]
mag gilaks rom daechireba gadadis mtavari gverdis meore tabze, sadac
spinerebs daayeneb. ertidaigive manqana imati shecdomaa. aqet unaklod
mushaobs :-)

**Comment by kujma10-zz** [comment]
მაგ ღილაკზე არ გეუბნები. მეორე ტაბზე რო გადახვალ და ფილრს დააჭერ იმ ღილაკზე

**Comment by gkiko** [comment]
ჰო მაგას სწორად მიხვდი.

**Comment by gkiko** [comment]
@kujma10 ეს დიდი issue გამოვიდა. რას აკეთებ კონკრეტულად ეხლა?

**Comment by kujma10-zz** [comment]
არაფერს

**Comment by kujma10-zz** [comment]
რანაირად მიხვდი სწორად. მეორე ტაბის ღილაკს აჭერ და ისევ მეორე ტაბზე გადადის სადაც სპინერები უნდა დააყენო ? (facepalm)

**Comment by kujma10-zz** [comment]
აა, ჩემი ნათქვამი იყო სწორი? ხო გასაგებია :D

**Comment by kujma10-zz** [comment]
და რატომ გამოვიდა დიდი იშუ? ახლების გამოტანა დაწერილია.
ისე მგონი ჯობია ეს შენ აიღო იმიტო რო ამ კლასში რეები წერია შენ ხარ აზრზე, და მე ისეთს ავიღებ რომელიც დაწყებულიც არაა საერთოდ, მაგალითად კატალოგს

**Comment by kujma10-zz** [comment]
ხვალ შევიკრიბოთ ვაბშე, ბევრი კითხვა მაწუხებს :დ

**Comment by gkiko** [comment]
@Jilberta
