### ISSUE TITLE
Car Page: რა მონაცემები უნდა ვაჩვენოთ და რა არა . . .

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#25]
ანუ გასარკვევია რა მონაცემებია საჭირო გამოსატანი და რა არა, და კიდე საიტზე გადამისამართება უნდა გავაკეთოთ, ჩემი აზრით, აუცილებელია  . . .

**Comment by gkiko** [comment]
გაირკვა ლაშასთან შეხვედრის შემდეგ
