### ISSUE TITLE
Catalog Page: Catalog View Page კითხვები

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#35]
ეს Catalog View Page გვერდი ბოლომდე გარკვეული არ არის, გასარკვევია რა ცხრილები უნდა გამოვიტანოთ და იქნება თუ არა გადამისამართება საიტზე და ასე შემდეგ . . .

**Comment by gkiko** [comment]
გაირკვა ლაშასთან შეხვედრის შემდეგ
