### ISSUE TITLE
Main Page: მოვაშოროთ search ტაბი

### ISSUE THREAD

**Issue by gkiko** [gkiko/MyAuto#40]
Main-ზე რომ შეხვალ, ჩანს 2 ტაბი. პირველი ტაბი უნდა დარჩეს, მეორე ტაბი უნდა მოშორდეს და მხოლოდ მაშინ გადავალთ მეორე ტაბის გვერდზე, თუ First page-ზე Search ღილაკს დაეჭირება.

**Comment by gkiko** [comment]
@kujma10

**Comment by Jilberta** [comment]
kikoool, moshorebas ar jobia ro axali davcerot da eg davtovot . . . ra ici ra xdeba iqneba da egeti dizain unda im tips.

chemi azrit, uketesi iqneba tu axal klass shevqmnit, gadavakopirebt mag kods mtlianad iq da mere movashorebt iq da manifestshi ubralod shevcvlit Activity-s ra da exlandeli kodi prosta iyos mere cavshalot  . . .

**Comment by gkiko** [comment]
gavamzade ukve da vtvirtav exla

**Comment by Jilberta** [comment]
ok
