### ISSUE TITLE
Login სისტემა

### ISSUE THREAD

**Issue by kujma10-zz** [gkiko/MyAuto#62]
ნებისმიერ მომხმარებელს უნდა შეეძლოს ლოგინი, რათა დაამატოს ახალი მანქანები.
დაწერილია:
1) შეიქმნას მასტერის გვერდი, რომელშიც იქნება მენიუ და ამ მენიუში იქნება ლოგინის ღილაკი
ამ გვერდის შვილი გახდება ყველა სხვა გვერდი.
2) შეიქმნას ლოგინის დიალოგის ლეიაუთი, რომელიც გამოიძახება ლოგინის ღილაკის დაჭერის შემდეგ

გასაკეთებელია:
1) უნდა დაიწეროს ფუნქცია ბაზაში შემოწმების (დიალოგის OK ღილაკის დაჭერისას) (საჭიროა აპი!!)
2) თუ წარმატებით დალოგინდა, მენუში ლოგინის ღილაკის მაგივრად უნდა გამოჩნდეს, მისალმების რამენაირი ფორმა და ახალი მანქანის დამატების ღილაკი, თუ არა კი შესაბამისი შეცდომა.

გასაკეთებელი რაც დარჩა, წესით ყველაფერი უნდა მოხდეს MasterPageActivity-ში.

**Comment by gkiko** [comment]
[ეს](http://developer.android.com/guide/topics/ui/dialogs.html#CustomLayout) გამოიყენე.
![asd](http://developer.android.com/images/ui/dialog_custom.png)

**Comment by gkiko** [comment]
დალოგინებისას **loading** ფანჯარა გამოუგდე
