### ISSUE TITLE
მომხმარებლის რეგისტრაცია

### ISSUE THREAD

**Issue by kujma10-zz** [gkiko/MyAuto#63]

**Comment by gkiko** [comment]
`Register` ღილაკის დაჭერისას გამოძახე ახალი გვერდი, რომელზეც საიტის შესაბამისი ფორმა იქნება შესავსები. აუცილებელი ველების შემოწმება უნდა ხდებოდეს. საბმითის შემდეგ მთავარ გვერდზე უნდა ბრუნდებოდეს.

**Comment by kujma10-zz** [comment]
@gkiko იმ ფაილში რეგისტრაციის request-იც კეთდება?

**Comment by gkiko** [comment]
კი, კეთდება და პასუხიც მოსდის html-ის სახით. რამენაირად უნდა გავარჩიოთ წარმატებით დარეგისტრირდა თუ წარუმატებლად.

**Comment by Jilberta** [comment]
@kujma10  kote daregistrirebis mere gamoatanine info ra ro an ver gaiaret registracia, an tu gaiara mashin daaloginos avtomaturad da gadaiyvanos pirvel gverdze

**Comment by kujma10-zz** [comment]
არ გვაქ მაგის აპი და იყოს ეგრე დროებით
