### ISSUE TITLE
MasterPageActivity: BUG

### ISSUE THREAD

**Issue by Jilberta** [gkiko/MyAuto#66]
ragaca problemaa, Search -ze ro gadadixar vabshe sxva content-s agdebs . . . .

dateste xolme ra kote da ise atvirtve brat !

**Comment by kujma10-zz** [comment]
`setContentView(R.layout.activity_search_page);`
`super.onCreate(savedInstanceState);`

ამ ორ ხაზს ადგილები უნდა შეეცვალოს

**Comment by gkiko** [comment]
ატვირთე შესწორებული კოდი უკვე?
