### ISSUE TITLE
SearchActivity Index out of bound

### ISSUE THREAD

**Issue by gkiko** [gkiko/MyAuto#73]
ფილტრში წელი რომ ავირჩიე და ოკ-ს დავაჭირე, 150-ე ხაზზე:
`java.lang.ArrayIndexOutOfBoundsException: length=1; index=2
`

**Comment by Jilberta** [comment]
kikol egeni dapauzebulia jer . . . .

gushin ro vtestavdit gafiltvras tu gaxsovs null ro ar yofiliyo String-ebis masivi  gavxadet 1 zomis da marto markebis mixedvit vtestavdit . . . .  

gadachrilia bugia mara kods ro avtvirtav mere davxurav issue-s
